apiVersion: v1
kind: Service
metadata:
  name: demoapp-service
spec:
  selector:
    app: demoapp
  externalTrafficPolicy: Local
  type: LoadBalancer
  ports:
    - name: default
      protocol: TCP
      port: 9000
      targetPort: 9000